/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const StakeLazyImport = createFileRoute('/stake')()
const SendLazyImport = createFileRoute('/send')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const StakeLazyRoute = StakeLazyImport.update({
  path: '/stake',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/stake.lazy').then((d) => d.Route))

const SendLazyRoute = SendLazyImport.update({
  path: '/send',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/send.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendLazyImport
      parentRoute: typeof rootRoute
    }
    '/stake': {
      id: '/stake'
      path: '/stake'
      fullPath: '/stake'
      preLoaderRoute: typeof StakeLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  SendLazyRoute,
  StakeLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/send",
        "/stake"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/send": {
      "filePath": "send.lazy.tsx"
    },
    "/stake": {
      "filePath": "stake.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
